# permissions for end users to view awsaccountbindingapprovals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsaccountbindingapproval-viewer-role
rules:
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingapprovals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingapprovals/status
  verbs:
  - get
