# permissions for end users to view awsaccountbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsaccountbinding-viewer-role
rules:
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindings/status
  verbs:
  - get
