# permissions for end users to view awsaccountbindingrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsaccountbindingrequest-viewer-role
rules:
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingrequests/status
  verbs:
  - get
