
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingrequests/finalizers
  verbs:
  - update
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindingrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindings/finalizers
  verbs:
  - update
- apiGroups:
  - integrations.opdev.io
  resources:
  - awsaccountbindings/status
  verbs:
  - get
  - patch
  - update
