# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/integrations.opdev.io_awsaccountbindingrequests.yaml
- bases/integrations.opdev.io_awsaccountbindings.yaml
- bases/integrations.opdev.io_awsaccountbindingapprovals.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_awsaccountbindingrequests.yaml
#- patches/webhook_in_awsaccountbindings.yaml
#- patches/webhook_in_awsaccountbindingapprovals.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_awsaccountbindingrequests.yaml
#- patches/cainjection_in_awsaccountbindings.yaml
#- patches/cainjection_in_awsaccountbindingapprovals.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
